[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedlot_contracts = "C4o4QSNLw5mpdwyJGr5JXuC2ZnukLNbLF6S5zLtGeucK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juandominguez/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest --detectOpenHandles"
