[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedlot_contracts = "5AZhBpUbTiZkqM2Z8LVTev8z6awDUGENeBvZYdjWVod9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest --detectOpenHandles"
