[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedlot_contracts = "2HTz6TXN6ERPGS3d5ZpYMjjR6bgpyTh1LjaXB543vEmp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juandominguez/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
