[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedlot_contracts = "842Eo9smCu8upye7yjHDBYrk8FF8utZPgPDYpMaJZsxT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juandominguez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
