[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seedlot_contracts = "AKN2JvdTDrpLXCBrGBirWXRmNiRq33kP3obE6gMFQJUZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/juandominguez/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest --detectOpenHandles"
